Работа со строкой запроса
htmlacademy-php/1439585-readme-12 pull request #13
Opened 2021-09-01 17:41 UTC by RedrikShukhart

2021-09-13 19:54 UTC, vzaiko-corcentric commented on functions.php
> +function showPostDate(int $key, string $dateAdd) : array
а зачем в этой функции нужен параметр key ?

2021-09-13 19:54 UTC, vzaiko-corcentric commented on index.php
>  date_default_timezone_set('Europe/Moscow');
- это настройку мне кажется лучше вынести в конфиг

- в dbConnect ты подключаешь dbconfig.php а файл конфига называется dbСonfig.php может ли это привезти к проблемам ?

2021-09-13 19:54 UTC, vzaiko-corcentric commented on index.php
> +    $cards = fetchAll($sqlСards, $connect);
sql формируется либо в if или в else затем передается в функцию fetchAll. Зачем нужен в if или else вызов fetchAll (можно ли его оттуда вынести?)

2021-09-13 19:54 UTC, vzaiko-corcentric commented on post.php
> +$isPostExsist = fetchAll("SELECT * from posts WHERE id={$postId};", $connect);
а вот тут очнь опасно так делать, так как таким образом делаются sql иньекции, данные от пользователя надо проверять прежде чем что то подставлять в запрос.

2021-09-13 19:54 UTC, vzaiko-corcentric commented on post.php
> +$sqlPublishedPosts = "SELECT * FROM users  JOIN posts ON users.id = posts.author_id  WHERE users.id = {$authouId};";
каждый запрос это дорогостоящая по ресурсам операция, можно ли тут что то улучшить ?

2021-09-13 19:54 UTC, vzaiko-corcentric commented on templates/post-details.php
> +                            require_once('templates/post-link.php');
а представь как будет выглядеть этот if если у тебя будет 100 типов контента

2021-09-23 08:50 UTC, RedrikShukhart commented on index.php
> +    $cards = fetchAll($sqlСards, $connect);
да, действительно, через if можно же формировать только содержимое переменной $sqlСards, а вызов fetchAll вполне вызывается после

2021-09-23 08:56 UTC, RedrikShukhart commented on functions.php
> +function showPostDate(int $key, string $dateAdd) : array
изначально, когда писала функцию, думала, что работать с массивом через foreach будет с ключем($array as $key => $val), а в итоге без $key, и соответственно, думала, что буду передавать данный параметр в функцию. Пересмотрела, а он же не используется никак...убрала
надо еще раз обдумать на счет понимания работы foreach

2021-09-23 08:59 UTC, RedrikShukhart commented on templates/post-details.php
> +                            require_once('templates/post-link.php');
в целом, чтобы не плодить такое количество if, а нужна реализация выбора условия по конкретному параметру, то приходит на ум делать через switch-case, тем более что рассматривается сравнение с конкретными параметрами(тип контента в данном случае)

2021-09-23 09:02 UTC, RedrikShukhart commented on post.php
> +$sqlPublishedPosts = "SELECT * FROM users  JOIN posts ON users.id = posts.author_id  WHERE users.id = {$authouId};";
пересмотрела количество запросов, объединила некоторые из них по смыслу, по итогу осталось 3 запроса

2021-09-23 09:04 UTC, RedrikShukhart commented on post.php
> +$isPostExsist = fetchAll("SELECT * from posts WHERE id={$postId};", $connect);
добавила предварительную фильтрацию с filter_input до подстановки переменной $postId в запрос

2021-09-24 18:31 UTC, RedrikShukhart commented
внесла коррективы по замечаниям, плюс:
- переделала функцию showPostDate показа относительного времени в showDate через switch-case, чтобы можно было пользовать для других аналогичных ситуаций;
- изменила на странице index.php условие показа постов, для случая некорректного параметра или несуществующей категории показ страница-"заглушка"
- добавила показ кол-ва лайков и комментов на странице популярного

2021-10-03 07:50 UTC, vzaiko-corcentric requested changes

2021-10-03 07:50 UTC, vzaiko-corcentric commented on index.php
> +$cards = fetchAll($sqlСards, $connect);
- Это рабочий вариант, но немного сложный и с ним могут быть проблемы, тк например если в $_GET понадобится добавить какието параметры для других фильтров, он уже не будет NULL, но и значения для категории там не будет и получим  nothing-to-show. 
-  $categoryName = filter_input(INPUT_GET, 'categoryname', FILTER_SANITIZE_SPECIAL_CHARS); Этот параметр является id category, а почемуто называется categoryname ?
- если мы знаем что нам должен придти какойто id его просто можно привести к значению int, а так вообще в mysqli есть подготовленные запросы и плейсхолдеры для параметров, чтобы в запрос не попало ничего лишнего, это гораздо проще реализовать и использовать для защиты от sql инекций.

2021-10-03 07:50 UTC, vzaiko-corcentric commented on templates/post-details.php
> +                                    require_once('templates/post-link.php');
можно сократить, примерно так <?php require_once("templates/{$postType}.php");  ?> только конечно имя шаблона должно совпадать с значением переменной $postType

2021-10-03 07:50 UTC, vzaiko-corcentric commented on index.php
>  }
есть предложение вынести этот код из index в какуюто функцию, в index просто вызвать и получить значение рейтинга.

2021-10-03 07:50 UTC, vzaiko-corcentric commented on index.php
> -declare(strict_types=1);
эм а зачем удалила из index declare(strict_types=1); ?

2021-10-21 12:46 UTC, merged