выполненные некоторые пункты; для доработки
htmlacademy-php/1439585-readme-12 pull request #14
Opened 2021-11-14 19:49 UTC by RedrikShukhart

2021-12-01 10:24 UTC, sl1ptonit requested changes

2021-12-01 10:24 UTC, sl1ptonit commented on add.php
>              $sql = 'INSERT INTO posts (author_id, category_id, date_add, title, content ) VALUES (1, 1, NOW(), ?, ?);';
здесь и ниже, в запрос запрос нежелательно хардкодить значения, они должны подставляться в запрос после нужных проверок тк если что то поменяется то все сломается. У тебя же есть переменная в которой хранится id пользователя, а id категории можно получить сделав соответствующий запрос.

2021-12-01 10:24 UTC, sl1ptonit commented on add.php
> +            if ($_SERVER['REQUEST_METHOD'] == 'POST') {
уже выше есть проверка что обрабатывается POST запрос

2021-12-01 10:24 UTC, sl1ptonit commented on add.php
> +
не нужная строка

2021-12-01 10:24 UTC, sl1ptonit commented on for-test.php
> +        echo "<br>ДОЛЖНО РАБОТАТЬ ТОЛЬКО ПРИ ЗАГРГУЗКЕ КАРТИНКИ<br>";
а зачем тут echo ?

2021-12-01 10:24 UTC, sl1ptonit commented on functions.php
> +function prepairTags(string $hashtags)
prepareTags

2021-12-01 10:24 UTC, sl1ptonit commented on functions.php
> +function prepairData(array $fields): array
prepareData

2021-12-01 10:24 UTC, sl1ptonit commented on functions.php
> +    $mimeTypes = ['image/png', 'image/jpeg', 'image/gif'];
разрешенные типы данных к загрузке лучше выносить в конфиг чтобы легко можно было менять изменять

2021-12-01 10:24 UTC, sl1ptonit commented on templates/layout.php
> +                            <a class="header__post-button button button--transparent" href="/add.php">Пост</a>
add.php очень абстрактно что добавляет adding-post как было для шаблона мне кажется более понятным

2021-12-01 10:24 UTC, sl1ptonit commented on add.php
>  $categories = fetchAll($sqlCategories, $connect);
данные о соединении с базой лучше удалит тк это не безопасео светить свои настройки

$is_auth = rand(0, 1);
$user_name = 'Стас';  предлагаю вынести в какойнибудь конфиг проекта чтобы не использовать в каждом файле.

2021-12-01 20:19 UTC, sl1ptonit commented on for-test.php
> +        echo "<br>КАКАЯ-ТО ССЫЛКА ЕСТЬ";
дебаг не должен попадать в коммиты

2021-12-13 20:59 UTC, sl1ptonit commented
/*
 *
 * Рефакторинг index.php
*/ 

Надо сделать небольшой рефакторинг тк кода становится все больше и его надо немного оптимизировать.
В index.php предлагаю упрастить алгоритм выбоки данных для отображения:

db_config.php лучше вернуть, что то я тут погарячился

выбираем все категории, выбирку всех категорий оформляем через функцию, в index не должно быть sql кода


формирование переменной $categoryIdList мне кажется лишним тк все для вывода уже есть $categories, 
проверка с if (in_array($categoryId, $categoryIdList)) точно лишная.


$categoryId = filter_input(INPUT_GET, 'categoryid', FILTER_SANITIZE_NUMBER_INT);

если $categoryId существует выбираем карточки соответствующей категории в запросе нужну
сделать join (или может и left join) с рейтингом. Запрос данных нужно оформить через функцию 
результат работы которой присваевыется $cards для вывода данных.

если $categoryId не существует выбираем и выводим все карточки, в запросе нужну
сделать join (или может и left join) с рейтингом. Запрос данных нужно оформить через функцию 
результат работы которой присваевыется $cards для вывода данных.

если массив $cards пустой редиректим на nothing-to-show.php
функционал редиректа нодо вынести в функцию, которая должна принемать только
адрес страницы куда надо перекинуть пользователя.

подключаем нужные шаблоны, выводим данные.


У функций должно быть название название по которому можно понять что она делает и phpdoc 
c расширеным описанием, что делает функция, с описанием аргументов и типов данных которые она принемает.

Пример:

/**
 * Возвращает строку в  верхнем регистре
 * @param string $msg строка для вывода
 * @return string 
 */
function foo($msg = '') : string {
    return strtoupper($msg);
}


В коде комментарии тоже приветствуются.

/**
*
* add.php
*	
*/
При создании поста надо тоже надо коечто подправить, при переключении между цитата, ссылка, картинка
и тд нужно определять шаблон какой категории показывать и показывать его полностью, без выделения подшаблона для тэгов и 
загаловка тк при возникновении ошибки js скрипт не может определить на какой странице ошибка тк это общая часть и страница начинает глючить.

2022-01-09 20:20 UTC, sl1ptonit commented
index.php

В phpstorm надо установить и включить плагин PHP Annotations для анализа php кода, тогда phpstorm сам будет подчеркивать то, что написано не корректно. 

//index.php:27 не очень понятно зачем здесь нужно 'echo', проверь пожалуйста что возращает функция redirectOnPage. 
if (empty($cards)) {
    echo redirectOnPage('nothing-to-show.php');
}

getCardsOnCategory - название ok, но обычно используют с частицей 'By' (перевод 'по'), название функции 
получится: "получить карточки по категории", лучше соответствует текущему контексту, еще примеры getById(), getByName().

Sql запросы в getAllCardsContent и getCardsOnCategory надо отформатировать, сейчас все очень сжато и сложно читать.

Про добавление постов, Есть разные способы написания кода, процедурный, когда используется просто последовательность различных вызовов, функциональный когда эта самая последовательность более менее инкапсулирована в функции и последний вариант объектно-ориентирований, когда код работает в основном с объектами различных классов. У тебя код рабочий, но он получился скорее процедурным, в него сложно вносить изменения и разобраться как работает. Его немного надо переделать на функциональный. Чтобы читая название функций легче было понять функциональность и вносить изменения.

add.php?categoryname=photo
Название параметров в запросе лучше использовать через нижнее подчеркивание.

на 17 строке, не просто массив $fields, у тебя даже в комментарии указано, массив обязательных полей.

valEmptyField - если эта функция делает валидацию пустых полей лучше так и назвать, 
как пример здесь хорошо получилось: validatePictureFromUser.

В add.php у тебя есть массив $filds и первый аргумент у valEmptyField() тоже $fields но это разные данные и мне кажется должны называться по разному и название должно отрожать что они содержат.

В valEmptyField() переменная $k это название мало информативно и тебе не нужен второй форич, у тебя есть название поля, ты по ключу можешь проверить есть ли это поле в
массиве обязательных полей и если есть и оно пустое то записывать в массив ошибок. 

index.php:29 if ($_SERVER['REQUEST_METHOD'] == 'POST') - здесь лучше использовать строгое сравнение тк оно работает быстрее и сним будет меньше ошибок.

//Посмотри пожалуйста документацию зачем обычно используются фигурные скобки
$sql = "INSERT INTO posts (author_id, category_id, date_add, title, content ) VALUES ({$userId}, {$categoryId}, NOW(), ?, ?);";

index.php:117 echo redirectOnPage($redirectPage);  - уже комментировал подобный код выше.

2022-01-12 19:58 UTC, RedrikShukhart commented
поправила код по последним замечаниям;
по поводу переделывания кода на добавление постов в функциональный: отдельным блоков в файле add.php находятся все возможные проверки полей(сначала просто что не пустые, потом уже по конкретным полям, как они описаны по ТЗ), а затем уже в switch-case указывала функцию, в которой происходит добавление постов конкретных типов категорий. Вынесла отдельными вспомогательными функциями как добавление записи в БД самого поста, так и добавление записи хэштегов. Надеюсь, более менее адекватно получилось, во всяком случае много чего вынесла именно в функции из этого файла.

2022-01-16 20:58 UTC, sl1ptonit commented
add.php:34

if ($postType == $category['class_name']) {
            $categoryId = $category['id'];
        }
        
Тут в цикле проверяется условие значит теоритически условие может не сработать какое тогда будет значение переменной $categoryId дальше по коду ?
Если условие сработает будет ли дальше работать цикл и нужно ли это ?

validateEmptyField - нужно проверять не все обязательные поля, а поля в зависимости от категории страница, тк не совсем эффективно проверять cite-text или video-url
если пользователь ввел данные на странице "текст".

Два одинаковых условия if (empty($errorFields)) мне кажется лишним. Спокойно можно объединить.

addNewTextPost - и остальные подобные функции написаны с ошибкой принципов SOLID. Обязательно надо почитать и выучить, спрашивают на всех собеседованиях!
Ошибка заключается в том что одна функция делает очень много и добавляет пост и добавляет тэги и редирект делает это разные ответственности и должны быть разные функции,
с учетом что предыдущие отработали без ошибок.

При добавлении поста, если не заполнить теги, а они вроде не обезатьльное поле выдает ошибку: 
Fatal error: Uncaught TypeError: Return value of prepareTags() must be of the type array, null returned in /code/functions.php on line 187

Все коммиты по таске уже лучще объединить в один, тк их уже очень много и в некоторых из них нет смысла.

2022-02-22 17:33 UTC, sl1ptonit commented
в целом все хорошо, но следуещем пул реквесте нужна будет небольшая оптимизация в add.php строки:
$requiredFields = [];
$errorFields = validateEmptyField($_POST, $requiredFields);

повтаряются в каждом case, 5 раз по 2 практически идентичные строки, как можно оптимизировать чтобы не было этих 10 лишних строк кода, а у нас было только один раз упоминание о validateEmptyField, а $requiredFields инициализировался в зависимости от типа поста ?

2022-02-22 17:34 UTC, merged